services:
  envoy:
    # image: envoyproxy/envoy:v1.32-latest
    build:
      context: envoy
    depends_on:
      vector:
        condition: service_started
      app:
        condition: service_started
    container_name: envoy
    volumes:
      - ./envoy/envoy.yaml:/config/envoy.yaml
    networks:
      - envoynet
    ports:
      - "80:9000"
      - "19000:19000"
      - "19010:19010"
    environment:
      - DEBUG_LEVEL=info
      - USE_STATSD=true
      - SERVICE_NAME=app
      - SERVICE_PORT=80
      - LOG_PROCESSOR=vector
  app:
    image: kennethreitz/httpbin:latest
    container_name: app
    networks:
      - envoynet
    ports:
      - "9090:80"
  vector:
    image: timberio/vector:0.43.0-debian
    container_name: vector
    networks:
      - envoynet
    ports:
      - "8125:8125/udp"
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 200M
  k6:
    image: grafana/k6
    entrypoint: /bin/sh
    container_name: k6
    networks:
      - envoynet 
    #command: run -e RATE=500 -e DURATION=10s /tests/http_case_01.js -e MY_HOST='envoy' -e USER_IP='100.100.100.100' -e CASE=vector -e DOMAIN=kwaf-demo.test -e CUSTOM_USER_IP_HEADER=XFF -e EXPECTED_SIZE=204800 | tail -3 | head -1 |jq -r '.|([(.metrics.http_req_duration.values| (.avg),(."p(90)"),(."p(95)"),(.max)),.metrics.http_req_failed.values.rate])| @csv'
    command: /tests/start_k6.sh
    volumes:
      - ./k6:/tests
    depends_on:
      envoy:
        condition: service_started
networks:
  envoynet:
    driver: bridge
    name: test
